// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendLogProjekt.Data;

namespace TrendLogProjekt.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191022172830_FinalMigration")]
    partial class FinalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrendLogProjekt.Models.BandwithReports", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GeneratedLeads");

                    b.Property<int>("GeneratedLeads2");

                    b.Property<int>("ServerAllocation");

                    b.Property<int>("SubmittedTickets");

                    b.HasKey("ID");

                    b.ToTable("bandwithReports");
                });

            modelBuilder.Entity("TrendLogProjekt.Models.TopAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageLocation");

                    b.Property<string>("Location");

                    b.Property<int>("Money");

                    b.Property<string>("Name");

                    b.Property<string>("Occupation");

                    b.Property<string>("Status");

                    b.HasKey("AuthorId");

                    b.ToTable("topAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
